### ISSUE TITLE
Ldaps and logs 

### ISSUE THREAD

**Issue by hdep** [brenard/phplist-casldap-plugin#2]
Hello,

I am trying your plugin on Debian jessie with phplist 3.2.6.
I configured my ldap server (which is active directory 2012). I want to use LDAPs.
This setup works fine with other tools. 

Since I enabled the plugin, I can't load the admin page I do have error 500.

In order to troubleshoot the issue can you tell me if : 
- LDAPS is supported ?
- where does the plugin log in case of errors, ssl mismatch ?

Thank you for your help

**Comment by brenard** [comment]
Hi,

Yes, LDAPS is supported. You could also use STARTTLS. Concerning logs, this plugin use PhpList abstraction to log error, so the answer of your question is on your PhpList installation / configuration.
However, in case of error 500, you should have something in Apache's error.log.

Do you have installed phpCAS and NetLDAP2 (php-cas and php-net-ldap2 debian packages) ? This libs are required. Futhermore, please verify that version of php-net-ldap2 package is at least 2.0.12-1+deb8u1 because previous version cause fatal error (see [debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812788)).

**Comment by hdep** [comment]
Hello,

thank you for your fast answer. I really appreciate it.
I use the following package : 
ii  php-cas                        1.3.3-1                     all          Central Authentication Service client library in php
ii  php-net-ldap2                  2.0.12-1+deb8u1             all          PHP PEAR module for searching and manipulating LDAP-entries

Sadly, I don't have any information in my error.log file. 
This is weird, this morning I only have return code 200 but same issue. Firefox status is aborted on this URL
https://myserver/mailing/admin/ui/dressprow/css/all.min.css?v=1478120591

When configuring ModifierPhpCAS library path and Net_LDAP2 library path is the full path expected ? For now I use : 
/usr/share/php/CAS.php
/usr/share/php/Net/LDAP2.php

But seems without any help.

I'll try to get some logs.
Regards,

**Comment by hdep** [comment]
Hello,

first of all I needed I think the php-pear package. 
Now when I go on the admin page I get redirected to localhost has the cas_host variable is localhost.

Is there a way to use your plugin only for LDAP ? 

Thank you

**Comment by brenard** [comment]
No, this plugin is only for an authentification using CAS Service and LDAP is only used after to retrieve user's informations and superuser right.

However, I mean it's not really complicated to adapt this plugin to make a full LDAP authentication plugin. If I found time to make it, I will take a look.

**Comment by hdep** [comment]
Ok.
Thank you ! 
I close this issue then.
